### ISSUE TITLE
Cool but, My browser is not able to load this repo

### ISSUE THREAD

**Issue by aisivan36** [vandadnp/flutter-tips-and-tricks#10]
Great tips thanks, the only problem is I can't load this page entirely. I think it's too heavy to load on a single page causes browser to stuck.

**Comment by vandadnp** [comment]
Hello and thank you for the feedback, I completely agree that the README.md file has become too big! I will need to spend quite a big chunk of time on fixing it and I believe now is the right time to do that... I will fix this in the coming days and keep you updated!

**Comment by Chetan-Goyal** [comment]
I feel that doing all of these changes will take a lot of time. Instead of spending all of that time by only yourself, you can add a template in a separate branch for some tips and contributors (including me) can do on rest of the tips according to your posted format.

**Comment by vandadnp** [comment]
This work is now done. It did take a while but it's worth it. Thank you for raising this issue.
