### ISSUE TITLE
Integer range optimization

### ISSUE THREAD

**Issue by sullenel** [vandadnp/flutter-tips-and-tricks#11]
Hi. The extension method `to` could be made more optimized or idiomatic (since its return type is declared as `Iterable`) by avoiding unnecessary array creation. The code won't be as pretty though 😃  

https://github.com/vandadnp/flutter-tips-and-tricks/blob/4c11641aa5945582a8f5f496f8977a6fc3746854/source/integer-range-extension-in-dart.dart#L15-L19

vs

```dart
extension To on int {
  Iterable<int> to(int other, [bool inclusive = true]) sync* {
    if (other > this) {
      for (int i = this; i < other; i++) yield i;
    } else {
      for (int i = this; i > other; i--) yield i;
    }

    if (inclusive) yield other;
  }
}
```

**Comment by vandadnp** [comment]
Thank you for raising this. The goal of this tip was to show Dart's support for Python-like list comprehensions. There is a separate tip about synchronous generators which you can find [here](https://github.com/vandadnp/flutter-tips-and-tricks/blob/main/tipsandtricks/synchronous-generators-in-dart/synchronous-generators-in-dart.md).
