### ISSUE TITLE
Add the update to the release description

### ISSUE THREAD

**Issue by nivisi** [vandadnp/flutter-tips-and-tricks#21]
Hey! Thanks for a very cool repo ✌️

Would be nice if the release message contained the tip itself or at least a link to the new section. So if I see the release in the feed, I could just read it by entering the release page.

**Comment by vandadnp** [comment]
Hi @nivisi and thank you for your suggestion

I like that idea and I'll do that going forward. In the [latest release](https://github.com/vandadnp/flutter-tips-and-tricks/releases/tag/353) titled "Firestore Transactions in Flutter" I've added some description and a link to the tip itself. Do you find that OK?

**Comment by nivisi** [comment]
@vandadnp I think that's really good! Now I can read the tip right away. When I opened that big readme, it was lagging so I couldn't get to the tip fast. Now it's possible.

Thanks! Really like the work you do. Keep going ❤️

**Comment by vandadnp** [comment]
You're most welcome, and thank you for the suggestion. Have a great day. I'll close the issue and let me know if there is anything else I can help with.
