### ISSUE TITLE
Tip 196: Error Handling Value Passing

### ISSUE THREAD

**Issue by malmi** [vandadnp/flutter-tips-and-tricks#5]
About https://github.com/vandadnp/flutter-tips-and-tricks/tree/main#future-error-handling-in-dart

Maybe a note would be helpful, to use that with caution. The creation of the error-value could be expensive and with your approach, I would create that object all the time, even if I don't need it. That is the reason, as far as I know, to pass a creation function into it. Just my thought to avoid bad designs for newcomers to dart.

Thanks for all your tips, I like it a lot.

**Comment by vandadnp** [comment]
Hi @malmi and thank you for your comments. I will keep this in mind for the future tips. I'm glad you're enjoying the tips and tricks 🔥
